
- name: "copy script"
  copy: src=../../scripts/addnode.sh dest=/root/addnode.sh

- name: "add node to the cluster"
  shell: systemctl enable docker && systemctl start docker && systemctl enable kubelet.service && systemctl start kubelet.service && chmod +x /root/addnode.sh && sh /root/addnode.sh

