- name: "installing epel"
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: upgrade all packages
  yum: name=* state=latest

- name: "installing app"
  yum: pkg={{ item }}  state=latest
  with_items:
  - docker
  - rsync
  - openvpn
  - easy-rsa

#- name: "copying docker project"
#  synchronize: src=/root/proj dest=/root/proj
