- name: For each host, ssh-copy-id my ssh public keys to the host
  shell: "sshpass -p {{ ansible_ssh_pass }} ssh-copy-id {{ item }}"
  with_items: "{{ ssh_known_hosts }}"
  when: not (( ansible_ssh_pass is undefined ) or ( ansible_ssh_pass is none ) or ( ansible_ssh_pass | trim == ''))
  tags: 
  - sshcopy

- name: "apt-get update"
  apt:
        update_cache: yes

- name: "installing app"
  apt: pkg={{ item }}  state=present
  with_items:
  - vim
  - htop
  - iftop
  - docker
  - docker-compose
  - rsync

- name: "copying .bashrc"
  synchronize: src=/etc/bash.bashrc dest=/etc/bash.bashrc

- name: "copying docker project"
  synchronize: src=/root/proj dest=/root/proj
