- name: "repos sync"
  copy: src=/etc/yum.repos.d dest=/etc

#- name: "install crictl"
#  copy: src=/usr/bin/crictl dest=/usr/bin
#- name: "installing repos keys"
#  rpm_key:
#    key: https://packages.cloud.google.com/yum/doc/yum-key.gpg
#    state: present

- name: "disable selinux"
  shell: sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config && setenforce 0

- name: "enable ip_vs kernel module"
  shell: modprobe ip_vs && echo "ip_vs" > /etc/modules-load.d/ip_vs

- name: "installing kubernates"
  yum: pkg={{ item }}  state=latest
  with_items:
  - kubelet
  - kubeadm
  - kubectl

- name: "apply workaround for kubelet"
  copy: src=/etc/systemd/system/kubelet.service.d/10-kubeadm.conf dest=/etc/systemd/system/kubelet.service.d/
